### ISSUE TITLE
Updating to “atom-import-js@0.5.0” failed

### ISSUE THREAD

**Issue by jeanfredrik** [Galooshi/atom-import-js#12]
I can’t update to the latest version. I’m not sure if this is an issue specific to this package, or something wrong with Atom or my setup, but updating other packages works fine. Here’s the output from Atom’s updater:

```
> sqlite3@3.1.8 install /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --module=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64' (1)
/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4
`-- (empty)


(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/electron-v1.3-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and electron@1.3.13 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/sqlite3.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "build" "--fallback-to-build" "--module=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64"
gyp ERR! cwd /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --module=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 16.4.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/node_modules/atom-import-js/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.4.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/package.json'
npm WARN apm-install-dir-11717-93563-omndu4 No description
npm WARN apm-install-dir-11717-93563-omndu4 No repository field.
npm WARN apm-install-dir-11717-93563-omndu4 No README data
npm WARN apm-install-dir-11717-93563-omndu4 No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jeanfredrik/.atom/.apm/.apmrc" "--userconfig" "/Users/jeanfredrik/.atom/.apmrc" "install" "/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/d-11717-93563-12it01y/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-93563-omndu4/npm-debug.log
npm ERR! code 1
```

**Comment by trotzig** [comment]
Annoying. Sorry for the trouble this is causing you. I did have some issues related to installing sqlite3 while working on the update, but I wasn't seeing this error. Since this is related to building native extensions, it would help to know what OS and Node version you are on. Also, can you try running `npm install sqlite3` separately? That could give us some more hints on how to solve this. 

Thanks for taking the time to report the issue 👍

**Comment by jeanfredrik** [comment]
Thanks for the reply! I’m on macOS Sierra 10.12.3, node v7.4.0. Do you mean a global install with `npm install -g sqlite3`? I’ve tried that now but with no luck.

**Comment by trotzig** [comment]
Yes. Do you get the same error?

**Comment by trotzig** [comment]
That command won't make the plugin work, I just want to see if this can be directly linked to installing `sqlite3` or not.

**Comment by jeanfredrik** [comment]
I think it’s the same error:

```
> sqlite3@3.1.8 install /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --module=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64' (1)
/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9
`-- (empty)


(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/electron-v1.3-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and electron@1.3.13 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/sqlite3.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "build" "--fallback-to-build" "--module=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64"
gyp ERR! cwd /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --module=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 16.4.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/node_modules/atom-import-js/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.4.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/package.json'
npm WARN apm-install-dir-11717-1518-1erhvp9 No description
npm WARN apm-install-dir-11717-1518-1erhvp9 No repository field.
npm WARN apm-install-dir-11717-1518-1erhvp9 No README data
npm WARN apm-install-dir-11717-1518-1erhvp9 No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jeanfredrik/.atom/.apm/.apmrc" "--userconfig" "/Users/jeanfredrik/.atom/.apmrc" "install" "/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/d-11717-1518-ttedm9/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11717-1518-1erhvp9/npm-debug.log
npm ERR! code 1
```

**Comment by trotzig** [comment]
It looks like this might be related/helpful: https://github.com/Homebrew/legacy-homebrew/issues/28442

It would be helpful if you could look into what version of libtool you use. Perhaps it's as simple as upgrading or temporarily reverting to a system default. 

It's unfortunate that atom-import-js has this dependency. I'll keep my eyes open for solutions to this that are more cross-os friendly.

**Comment by trotzig** [comment]
Any news on this @jeanfredrik? 🇸🇪

**Comment by jeanfredrik** [comment]
I was using the system default version on libtool in `/usr/bin/libtool/`. I tried installing it via Homebrew (which prepends it with "g" to avoid conflict with Apple’s libtool) and then make a symbolic link from `/usr/local/bin/libtool` to `/usr/local/Cellar/libtool/2.4.6_1/bin/glibtool`.

With the system default libtool I can’t run `libtool --help`, but with the new version I can. But I still can’t upgrade the package in Atom.

```
> sqlite3@3.1.8 install /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
Usage: /usr/local/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --module=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64' (1)
/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8
`-- (empty)


node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/electron-v1.3-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and electron@1.3.13 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
libtool:   error: unrecognised option: '-static'
make: *** [Release/sqlite3.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "build" "--fallback-to-build" "--module=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64"
gyp ERR! cwd /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --module=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 16.4.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/node_modules/atom-import-js/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.4.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/package.json'
npm WARN apm-install-dir-11719-51477-l1dic8 No description
npm WARN apm-install-dir-11719-51477-l1dic8 No repository field.
npm WARN apm-install-dir-11719-51477-l1dic8 No README data
npm WARN apm-install-dir-11719-51477-l1dic8 No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jeanfredrik/.atom/.apm/.apmrc" "--userconfig" "/Users/jeanfredrik/.atom/.apmrc" "install" "/private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/d-11719-51477-pp1lff/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/8w/vyccth4s0xj_1zsm9ljkw7_00000gq/T/apm-install-dir-11719-51477-l1dic8/npm-debug.log
npm ERR! code 1
```

**Comment by jeanfredrik** [comment]
@trotzig Anything more I can try?

**Comment by trotzig** [comment]
Sorry I left you in the dark here. Could you try some of the solutions listed here? https://github.com/mapbox/node-sqlite3/wiki/Binaries

If not, I think I'll consider removing the dependency on the sqlite3 npm package in favor of something that doesn't require a native binary. 

Sorry you have to go through all of this. Hopefully we can find a solution that will benefit others using the tool.

**Comment by jeanfredrik** [comment]
I have found a solution now! It was related to libtool. I had to use the version that ships with Xcode, so I made a symlink from `/usr/local/bin/libtool` to `/Library/Developer/CommandLineTools/usr/bin/libtool`. Don’t know why it didn’t work out of the box for me, but now the update ran smoothly.

Thanks for your patience and support! Please let me know if you want any help with migrating from the sqlite3 npm package.

**Comment by trotzig** [comment]
Awesome! Glad you figured out a solution. I'll keep an eye out for others who might run into the same issue. If many people do, then we can consider moving off of sqlite3.
