### ISSUE TITLE
Osx cannot install package

### ISSUE THREAD

**Issue by m-pokrovskii** [Galooshi/atom-import-js#15]
```
Installing “atom-import-js@0.6.1” failed.Hide output…

> sqlite3@3.1.8 install /private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --module=/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64' (1)
/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor
`-- (empty)


node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/electron-v1.3-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and electron@1.3.13 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/sqlite3.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "build" "--fallback-to-build" "--module=/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64"
gyp ERR! cwd /private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --module=/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/node_modules/atom-import-js/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/package.json'
npm WARN apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor No description
npm WARN apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor No repository field.
npm WARN apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor No README data
npm WARN apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mpokrovskii/.atom/.apm/.apmrc" "--userconfig" "/Users/mpokrovskii/.atom/.apmrc" "install" "/private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/d-11749-11974-1kgp97x.f12mwh4cxr/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/_2/x5857l3j0c1cqk5cphrgt22m0000gn/T/apm-install-dir-11749-11974-1vc5bt7.za5b0dlsor/npm-debug.log
npm ERR! code 1

```

**Comment by trotzig** [comment]
We had a similar issue a while back: https://github.com/Galooshi/atom-import-js/issues/12

I hope there's something in there that can help you get things resolved!
