### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by reohjs** [Galooshi/atom-import-js#17]
[Enter steps to reproduce:]

1. Try to activate any of the 3 commands

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional (64-bit)
**Thrown From**: [atom-import-js](https://github.com/galooshi/atom-import-js) package 0.6.1

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```cmd
At path.js:64

RangeError: Maximum call stack size exceeded
    at String.slice (native)
    at normalizeStringWin32 (path.js:64:22)
    at Object.normalize (path.js:403:14)
    at Object.join (path.js:527:18)
    at findRecursive (/packages/atom-import-js/node_modules/import-js/build/findProjectRoot.js:28:10)
    (then the above line repeated as many times as possible)
    at findProjectRoot (/packages/atom-import-js/node_modules/import-js/build/findProjectRoot.js:39:10)
    at withModuleFinder (/packages/atom-import-js/lib/withModuleFinder.js:6:26)
    at importWord (/packages/atom-import-js/lib/import-js.js:112:3)
    at /packages/atom-import-js/lib/import-js.js:150:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Non-Core Packages

```
atom-import-js 0.6.1 
autocomplete-modules 1.6.9 
file-type-icons 1.3.3 
file-types 0.5.5 
language-babel 2.57.1 
language-javascript-semantic 0.2.1 
linter 1.11.23 
linter-eslint 8.1.7 
pigments 0.39.1 
project-manager 3.3.4 
shortcuts 0.1.0 
simple-drag-drop-text 0.3.4 
windows-build-tools 1.0.0 
```

**Comment by reohjs** [comment]
I looked at this more closely and noticed it's an issue with import-js so I'll make an issue over there instead.
