### ISSUE TITLE
Issue when trying to install atom-impor-js

### ISSUE THREAD

**Issue by benonymus** [Galooshi/atom-import-js#27]
Hey I get this error when I try to install it on windows 10.
`Installing “atom-import-js@0.12.0” failed.Hide output…

> sqlite3@3.1.13 install C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\node_modules\atom-import-js\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

Failed to execute 'C:\Users\benonymus\AppData\Local\atom\app-1.21.2\resources\app\apm\bin\node.exe C:\Users\benonymus\AppData\Local\atom\app-1.21.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\node_modules\atom-import-js\node_modules\sqlite3\lib\binding\electron-v1.6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\node_modules\atom-import-js\node_modules\sqlite3\lib\binding\electron-v1.6-win32-x64' (1)
C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr
`-- (empty)

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.6-win32-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and electron@1.6.15 (electron-v1.6 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\benonymus\AppData\Local\atom\app-1.21.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\benonymus\AppData\Local\atom\app-1.21.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\benonymus\AppData\Local\atom\app-1.21.2\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\benonymus\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\benonymus\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\BENONY~1\\AppData\\Local\\Temp\\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\\node_modules\\atom-import-js\\node_modules\\sqlite3\\lib\\binding\\electron-v1.6-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\BENONY~1\\AppData\\Local\\Temp\\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\\node_modules\\atom-import-js\\node_modules\\sqlite3\\lib\\binding\\electron-v1.6-win32-x64"
gyp ERR! cwd C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\node_modules\atom-import-js\node_modules\sqlite3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\benonymus\AppData\Local\atom\app-1.21.2\resources\app\apm\bin\node.exe C:\Users\benonymus\AppData\Local\atom\app-1.21.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\node_modules\atom-import-js\node_modules\sqlite3\lib\binding\electron-v1.6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\node_modules\atom-import-js\node_modules\sqlite3\lib\binding\electron-v1.6-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\node_modules\atom-import-js\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Users\\benonymus\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\BENONY~1\\AppData\\Local\\Temp\\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\\node_modules\\atom-import-js\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\node_modules\atom-import-js\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\package.json'
npm WARN apm-install-dir-117107-6440-1akc8tq.1n10olmcxr No description
npm WARN apm-install-dir-117107-6440-1akc8tq.1n10olmcxr No repository field.
npm WARN apm-install-dir-117107-6440-1akc8tq.1n10olmcxr No README data
npm WARN apm-install-dir-117107-6440-1akc8tq.1n10olmcxr No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\benonymus\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\benonymus\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\benonymus\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\benonymus\\.atom\\.apmrc" "install" "C:\\Users\\BENONY~1\\AppData\\Local\\Temp\\d-117107-6440-wojvzz.as00r1wcdi\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.13 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\BENONY~1\AppData\Local\Temp\apm-install-dir-117107-6440-1akc8tq.1n10olmcxr\npm-debug.log
npm ERR! code 1`

**Comment by trotzig** [comment]
Hi @benonymus, sorry you're having issues installing the plugin. The sqlite dependency is known to be a little shaky. Here are a few previous issues filed on similar errors: 
https://github.com/Galooshi/atom-import-js/issues/12
https://github.com/Galooshi/atom-import-js/issues/15

None of those are on windows though, but there might be things in those thread that could help you. The first thing I would try is to install python and try again, as suggested by the error message: 

>  stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

**Comment by moranda** [comment]
I could solve this problem on windows by adding a new PYTHON environment variable.
(Control Panel » System » Advanced » Environment Variables)
