### ISSUE TITLE
Failed to load the atom-import-js package

### ISSUE THREAD

**Issue by strongant** [Galooshi/atom-import-js#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-import-js](https://github.com/galooshi/atom-import-js) package, v0.2.0

### Stack Trace

Failed to load the atom-import-js package

```
At Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/devbwh/.atom/packages/atom-import-js/lib/import-js.js:10:21)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.19
atom-import-js, v0.2.0
atom-jshint, v2.0.0
atom-terminal-panel, v4.4.4
atom-ternjs, v0.13.2
atomic-chrome, v0.3.0
autocomplete-modules, v1.4.1
emmet, v2.4.3
file-icons, v1.7.7
formatter-json, v1.0.1
jquery-snippets, v11.0.0
jsformat, v0.9.3
minimap, v4.23.5
run-in-browser, v0.1.3
sync-settings, v0.7.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by lencioni** [comment]
Thanks for the report! Can you try updating to Atom 1.7.3 and atom-import-js 0.2.1 and let us know if that changes anything?

**Comment by strongant** [comment]
ok,let me hava a try.

**Comment by strongant** [comment]
thank you . I hava already resolved it.

**Comment by dmitrizzle** [comment]
Same issue with Atom 1.40.0 and atom-import-js v0.21.0

**Comment by dmitrizzle** [comment]
Should this not be reopened?

**Comment by georgemac510** [comment]
> Should this not be reopened?

Having same issue.
