### ISSUE TITLE
Can't install atom-import-js (Python 3)

### ISSUE THREAD

**Issue by kykungz** [Galooshi/atom-import-js#36]
Hi, I'm trying to run `apm install atom-import-js` and got this error message:

```bash
> sqlite3@4.0.0 install /private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp configure --fallback-to-build --module=/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64 --node_abi_napi=electron-v1.7 --python=/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh' (1)
/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29
└── (empty)


node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.7-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@4.0.0 and electron@1.7.15 (electron-v1.7 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "configure" "--fallback-to-build" "--module=/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64" "--node_abi_napi=electron-v1.7" "--python=/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"
gyp ERR! cwd /private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp configure --fallback-to-build --module=/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64 --node_abi_napi=electron-v1.7 --python=/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/node_modules/atom-import-js/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/package.json'
npm WARN apm-install-dir-118518-94052-1h8wdjr.h9b3dte29 No description
npm WARN apm-install-dir-118518-94052-1h8wdjr.h9b3dte29 No repository field.
npm WARN apm-install-dir-118518-94052-1h8wdjr.h9b3dte29 No README data
npm WARN apm-install-dir-118518-94052-1h8wdjr.h9b3dte29 No license field.
npm ERR! Darwin 17.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/kongpon-macbook/.atom/.apm/.apmrc" "--userconfig" "/Users/kongpon-macbook/.atom/.apmrc" "install" "/private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/d-118518-94052-9y7m93.eol28x5hfr/package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@4.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/s5/8rx6q8sd1z14vv2nsh135pww0000gn/T/apm-install-dir-118518-94052-1h8wdjr.h9b3dte29/npm-debug.log
npm ERR! code 1
```

How could I fix it? I personally don't write python, but I have python2 and 3 installed in my mac using anaconda (however, I have no idea how to switch or even use it)

I tried searching for how to change python version (found `source activate py27`) but it doesn't seem to work.

**Comment by trotzig** [comment]
Hi @kykungz, thanks for using import-js! I don't have a ready-made solution for your problem, but you can try some workarounds found by others: 

https://github.com/Galooshi/atom-import-js/issues/27#issuecomment-373870748
https://github.com/Galooshi/atom-import-js/issues/12#issuecomment-281944462
