### ISSUE TITLE
Failed to activate the atom-import-js package

### ISSUE THREAD

**Issue by dannyyy-jimenez** [Galooshi/atom-import-js#39]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [atom-import-js](https://github.com/galooshi/atom-import-js) package 0.21.0

### Stack Trace

Failed to activate the atom-import-js package

```
At Cannot find module '/Users/daniel/.atom/packages/atom-import-js/node_modules/sqlite3/lib/binding/electron-v2.0-darwin-x64/node_sqlite3.node'

Error: Cannot find module '/Users/daniel/.atom/packages/atom-import-js/node_modules/sqlite3/lib/binding/electron-v2.0-darwin-x64/node_sqlite3.node'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/atom-import-js/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at /packages/atom-import-js/node_modules/sqlite3/lib/sqlite3.js:190:3)
    at Module.get_Module._compile (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/atom-import-js/node_modules/import-js/build/ExportsStorage.js:8:38)
    at /packages/atom-import-js/node_modules/import-js/build/ExportsStorage.js:423:3)
    at Module.get_Module._compile (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/atom-import-js/node_modules/import-js/build/ModuleFinder.js:14:46)
    at /packages/atom-import-js/node_modules/import-js/build/ModuleFinder.js:359:3)
    at Module.get_Module._compile (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/private/var/folders/k2/9__zh42x0h93t11vdr8mmx900000gn/T/AppTranslocation/5A422191-FFD5-496C-9AE0-64F41038452C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ide-ui 0.13.0 
atom-import-js 0.21.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-ternjs 0.18.3 
atom-typescript 12.5.3 
auto-close-html2 0.7.0 
busy-signal 2.0.0 
custom-folds 1.9.5 
emmet 2.4.3 
file-icons 2.1.28 
fonts 3.2.0 
gl-light-syntax 3.0.0 
intentions 1.1.5 
line-count 0.5.0 
linter 2.3.0 
linter-eslint 8.5.0 
linter-jshint 3.1.11 
linter-tslint 1.10.4 
linter-ui-default 1.7.1 
pigments 0.40.2 
restart-atom 0.2.0 
seti-ui 1.11.0 
teletype 0.13.3 
terminal-tab 0.5.7 
todo-show 2.3.2 
```

**Comment by trotzig** [comment]
Could this be the same root cause as https://github.com/Galooshi/atom-import-js/issues/12 ?

**Comment by nickpresta** [comment]
I can confirm I'm getting the same issue on Atom 1.39.0-beta3:

**Atom**: 1.39.0-beta3 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-import-js](https://github.com/galooshi/atom-import-js) package 0.21.0


### Stack Trace

Failed to activate the atom-import-js package

```
At Cannot find module '/Users/npresta/.atom/packages/atom-import-js/node_modules/sqlite3/lib/binding/electron-v3.1-darwin-x64/node_sqlite3.node'

Error: Cannot find module '/Users/npresta/.atom/packages/atom-import-js/node_modules/sqlite3/lib/binding/electron-v3.1-darwin-x64/node_sqlite3.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:155394)
    at Module.require (/app.asar/static/index.js:60:43)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:146719)
    at /packages/atom-import-js/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at /packages/atom-import-js/node_modules/sqlite3/lib/sqlite3.js:190:3)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:146719)
    at /packages/atom-import-js/node_modules/import-js/build/ExportsStorage.js:8:38)
    at /packages/atom-import-js/node_modules/import-js/build/ExportsStorage.js:423:3)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:146719)
    at /packages/atom-import-js/node_modules/import-js/build/ModuleFinder.js:14:46)
    at /packages/atom-import-js/node_modules/import-js/build/ModuleFinder.js:359:3)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-import-cost 1.2.0 
atom-import-js 0.21.0 
atom-typescript 13.2.1 
autocomplete-python 1.14.1 
blame 1.1.0 
busy-signal 2.0.1 
django-templates 0.5.0 
ex-mode 0.18.0 
file-icons 2.1.33 
go-debug 1.6.2 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
hyperclick 0.0.0 
ide-go 0.12.3 
ide-python 1.4.1 
ide-typescript 0.9.1 
intentions 1.1.5 
js-hyperclick 1.13.3 
language-babel 2.85.0 
language-docker 1.1.8 
language-dotenv 1.2.0 
language-graphql 1.0.0 
language-groovy 0.7.0 
language-haml 0.32.1 
language-ini 1.21.0 
language-jq 0.2.0 
language-nginx 0.8.0 
language-proto 0.8.0 
language-rspec 0.12.1 
linter 2.3.0 
linter-eslint 8.5.5 
linter-flake8 2.4.0 
linter-mypy 2.6.4 
linter-rubocop 2.4.2 
linter-ruby 1.3.1 
linter-ui-default 1.7.1 
MagicPython 1.1.1 
prettier-atom 0.57.0 
python-black 0.7.0 
ruby-block 0.3.6 
sort-lines 0.19.0 
vim-mode-plus 1.36.0 
```

**Comment by mendelgusmao** [comment]
Reinstalling the package worked for me.

**Comment by bennypowers** [comment]
Reinstalling, unfortunately, did not solve the problem for me on 1.41-0.nightly3

**Atom**: 1.41.0-nightly3 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.5
**Thrown From**: [atom-import-js](https://github.com/galooshi/atom-import-js) package 0.21.0


### Stack Trace

Failed to activate the atom-import-js package

```
At Cannot find module '/Users/bennyp/dotfiles/atom/packages/atom-import-js/node_modules/sqlite3/lib/binding/electron-v4.2-darwin-x64/node_sqlite3.node'

Error: Cannot find module '/Users/bennyp/dotfiles/atom/packages/atom-import-js/node_modules/sqlite3/lib/binding/electron-v4.2-darwin-x64/node_sqlite3.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom Nightly.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-import-js/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at /packages/atom-import-js/node_modules/sqlite3/lib/sqlite3.js:209:3)
    at Module.get_Module._compile (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-import-js/node_modules/import-js/build/ExportsStorage.js:8:38)
    at /packages/atom-import-js/node_modules/import-js/build/ExportsStorage.js:423:3)
    at Module.get_Module._compile (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-import-js/node_modules/import-js/build/ModuleFinder.js:14:46)
    at /packages/atom-import-js/node_modules/import-js/build/ModuleFinder.js:359:3)
    at Module.get_Module._compile (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.33.4 
atom-black-syntax 0.15.0 
atom-html-preview 0.2.6 
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-import-cost 1.2.0 
atom-import-js 0.21.0 
atom-inline-blame 0.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-typescript 13.2.1 
autocomplete-haskell 1.0.1 
autocomplete-js-import 1.4.0 
autocomplete-module-import 0.3.0 
autocomplete-paths 2.12.2 
busy-signal 2.0.1 
choose-pane 0.8.0 
color-picker 2.3.0 
counter 0.3.5 
docblockr 0.13.7 
duplicate-removal 0.1.3 
emmet 2.4.3 
file-icons 2.1.33 
framer-syntax 1.1.0 
framer-ui 2.0.0 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
git-blame 1.8.0 
git-time-machine 2.1.0 
gitlab-integration 0.4.8 
GobbieGobGoo 1.0.4 
haskell-debug 0.3.6 
haskell-ghc-mod 2.2.5 
haskell-pointfree 0.2.0 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.16.0 
ide-bash 1.0.11 
ide-cpp 0.1.0 
ide-css 0.3.2 
ide-haskell 2.4.0 
ide-haskell-cabal 2.2.1 
ide-haskell-hasktags 0.0.16 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.8.7 
ide-ruby 0.3.0 
ide-typescript 0.9.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
intentions-colorpicker 1.0.1 
intentions-numbers 1.0.4 
language-fish-shell 1.1.0 
language-github-actions 0.1.0 
language-graphql 1.0.0 
language-haskell 1.19.0 
language-ini 1.21.0 
less-than-slash 0.19.0 
linter 2.3.0 
linter-codeclimate 0.3.0 
linter-docker 0.3.2 
linter-eslint 8.5.5 
linter-jsonlint 1.4.0 
linter-npm-missing 1.0.1 
linter-php 1.6.1 
linter-pylint 2.1.1 
linter-rubocop 2.4.2 
linter-sass-lint 1.9.0 
linter-stylelint 4.4.9 
linter-tslint 1.10.28 
midnight-owl-syntax 0.1.0 
minimap 4.29.9 
minimap-git-diff 4.3.1 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
new-moon-atom-syntax 2.0.9 
npm-library-description 1.3.4 
npm-outdated 0.6.0 
open-this 0.5.0 
pigments 0.40.2 
pristine-ui 1.1.11 
regex-railroad-diagram 0.19.4 
relative-numbers 0.9.0 
remember-folds 0.3.0 
remote-ftp 2.2.2 
split-diff 1.6.0 
teletype 0.13.4 
templatize-string 0.2.2 
terminal-tab 0.5.7 
tinacious-design-syntax 1.0.2 
vim-mode-plus 1.36.0 
vim-mode-plus-emmet-bindings 0.0.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by dmitrizzle** [comment]
Same issue here. Atom 1.39.1 atom-import-js 0.21.0

**Comment by janfigala** [comment]
Reinstalling worked for me as well. Thanks @mendelgusmao!

You can run `apm remove atom-import-js && apm install atom-import-js`.

```
atom-import-js: 0.21.0
Atom: 1.40.1
Electron: 3.1.10
Chrome: 66.0.3359.181
Node: 10.2.0
```

**Comment by pw1z** [comment]
Okay, late to this party.
For anyone else with this issue.  There **_IS_** a youtube video, short, but it solves the problem.
Basically uninstall the package and re-install it.
Close Atom - re-start it - problem gone (for me anyway)
[Failed to activate the pigments package in ATOM editor](https://www.youtube.com/watch?v=dRhXjz7-Rro)
