### ISSUE TITLE
Uncaught Error: /bin/sh: -c: line 0: syntax error near unexpected token `('/bin/sh: -c: line 0: ...

### ISSUE THREAD

**Issue by sunbird89629** [Galooshi/atom-import-js#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-import-js](https://github.com/galooshi/atom-import-js) package, v0.2.2
### Stack Trace

Uncaught Error: /bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0:`find . -name "*_.js_" -not -path "./node_modules/_" | egrep -i "(/|^)opportunity(es|s)?.?search(es|s)?.?result"(/index)?(/package)?.js._"'

```
At /Users/wang/.atom/packages/atom-import-js/node_modules/import-js/build/findMatchingFiles.js:45

Error: /bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `find . -name "**.js*" -not -path "./node_modules/*" | egrep -i "(/|^)opportunity(es|s)?.?search(es|s)?.?result"(/index)?(/package)?.js.*"'

  at findMatchingFiles (/Users/wang/.atom/packages/atom-import-js/node_modules/import-js/build/findMatchingFiles.js:45:11)
  at /Users/wang/.atom/packages/atom-import-js/node_modules/import-js/build/findJsModulesFor.js:88:37
  at Array.forEach (native)
  at findImportsFromLocalFiles (/Users/wang/.atom/packages/atom-import-js/node_modules/import-js/build/findJsModulesFor.js:87:29)
  at findJsModulesFor (/Users/wang/.atom/packages/atom-import-js/node_modules/import-js/build/findJsModulesFor.js:130:87)
  at Importer.findOneJsModule (/Users/wang/.atom/packages/atom-import-js/node_modules/import-js/build/Importer.js:278:54)
  at Importer._import (/Users/wang/.atom/packages/atom-import-js/node_modules/import-js/build/Importer.js:92:27)
  at inCurrentWorkingDirectory (/Users/wang/.atom/packages/atom-import-js/lib/import-js.js:122:70)
  at inCurrentWorkingDirectory (/Users/wang/.atom/packages/atom-import-js/lib/import-js.js:20:18)
  at importWord (/Users/wang/.atom/packages/atom-import-js/lib/import-js.js:122:18)
  at atom-workspace.subscriptions.add.atom.commands.add.import-js:import (/Users/wang/.atom/packages/atom-import-js/lib/import-js.js:159:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```
### Commands

```
     -0:44.6.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  4x -0:42.3.0 core:backspace (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:40.9.0 core:move-up (atom-text-editor.editor.power-mode.is-focused)
     -0:40.7.0 editor:delete-line (atom-text-editor.editor.power-mode.is-focused)
     -0:40.5.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:39.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.power-mode.is-focused)
  6x -0:36.1.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
  7x -0:28.1.0 core:move-left (atom-text-editor.editor.power-mode.is-focused)
     -0:26.4.0 editor:select-to-end-of-line (atom-text-editor.editor.power-mode.is-focused)
     -0:23.6.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
  2x -0:21.6.0 core:backspace (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:20.4.0 autocomplete-plus:cancel (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:20 core:save (atom-text-editor.editor.power-mode.is-focused)
  2x -0:19.6.0 editor:auto-indent (atom-text-editor.editor.power-mode.is-focused)
     -0:19.2.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:01.3.0 import-js:import (atom-text-editor.editor.power-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "closeEmptyWindows": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "atom-beautify",
      "preview-plus",
      "terminal-plus",
      "language-objective-c",
      "tree-view",
      "script",
      "autocomplete-modules",
      "linter"
    ],
    "packagesWithKeymapsDisabled": [
      "ever-notedown"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.6.0
aligner, v0.22.0
atom-alignment, v0.12.1
atom-import-js, v0.2.2
atom-react-native-autocomplete, v0.0.27
atomic-chrome, v0.3.0
console-log, v1.5.1
docblockr, v0.7.3
eclipse-keybindings, v0.9.0
ever-notedown, v0.2.22
file-icons, v1.7.15
fwd-back, v0.1.0
git-time-machine, v1.5.3
goto-last-edit, v0.3.2
highlight-selected, v0.11.2
indent-guide-improved, v1.4.9
js-hyperclick, v1.4.2
language-javascript-jsx, v0.3.7
linter-eslint, v7.2.4
merge-conflicts, v1.4.4
nuclide, v0.148.0
pretty-json, v1.4.1
react, v0.15.0
tidy-markdown, v3.0.1

# Dev
No dev packages
```

**Comment by trotzig** [comment]
Sorry that you didn't get a timely response to this. This bug should be fixed with the latest version.
